docs/performance.md
`Kubernetes Request lifecycle` section in `performance.md` is now a link to the docs located at the `lifecycle.md` file.
=> performance.md links to lifecycle.md

e2e-tests/tests.sh
Force e2e tests to run in minikube context.
=> Use minikube context in e2e tests

main.go
Before:
```
{"level":"error","ts":1549291244.970731,"caller":"k8s-metadata-injection/main.go:47","msg":"failed to load key pair","err":"open /etc/tls-key-cert-pair/tls.crt: no such file or d
irectory","stacktrace":"main.main\n\t/Users/smoya/go/src/github.com/newrelic/k8s-metadata-injection/main.go:47\nruntime.main\n\t/usr/local/Cellar/go/1.11.4/libexec/src/runtime/pr
oc.go:201"}
```
After:
```
{"level":"error","ts":"2019-02-04T16:39:50.680+0100","caller":"k8s-metadata-injection/main.go:49","msg":"failed to load key pair","err":"open /etc/tls-key-cert-pair/tls.crt: no s
uch file or directory","stacktrace":"main.main\n\t/Users/smoya/go/src/github.com/newrelic/k8s-metadata-injection/main.go:49\nruntime.main\n\t/usr/local/Cellar/go/1.11.4/libexec/s
rc/runtime/proc.go:201"}
```
=> Human readable timestamps in logs

webhook.go
A misspelt word has been found in a logline thanks to https://goreportcard.com/report/github.com/newrelic/k8s-metadata-injection
=> Fix minor typo in log

e2e-tests/k8s-e2e-bootstraping.sh, e2e-tests/tests.sh
* The bootstrapping code now is updated with the recent changes made in the cert-manager repository.
* The tests have been updated. Now are waiting for the setup job to become `Succeeded` as it will mean the webhook has been patched successfully.
=> Avoid E2e potential race

LICENSE
In order to be compatible with Github License detection, we should use the long Apache 2.0 LICENSE file.
=> Update LICENSE template accordingly to Github.

cmd/server/main.go, deploy/newrelic-metadata-injection.yaml
This is required for the metadata injection to work with OpenShift.
=> Run the webhook server on port 8443 to avoid need for root user

cmd/server/main.go
This value doesn't care anymore about the timeout sent via URL parameter by the Kubernetes API server.
This is done to minimize the impact when, for whatever reason, the API server cannot properly reach the webhook server.
It's also possible to change this timeout via environment variables.
=> Change the default server timeout to 1s

.github/workflows/build.yml
Upgrade `manusa/actions-setup-minikube` to use the latest version.
GitHub is rolling out Ubuntu 20.04 as the default environment. GitHub actions workflows using `ubuntu-latest` will [soon ](https://github.com/actions/virtual-environments/issues/1816) start an Ubuntu 20,04 instance instead of 18.04.
Prior versions of `manusa/actions-setup-minikube` have a check which won't allow the workflow job to run. Starting on `2.2.0`, Ubuntu 20.04 is supported too (https://github.com/manusa/actions-setup-minikube/issues/26).
=> ci: Upgrade actions-setup-minikube to v2.3.0

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/deployment.yaml
`selector` is immutable and the previous chart did not have all the idiomatic labels so `nri-bundle` is failing to upgrade charts.
=> Fix immutable selector

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/nri-metadata-injection/templates/deployment.yaml, charts/nri-metadata-injection/values.yaml
This chart was ignoring `global.images.pullSecrets` because it was testing only the local ones.
This should fix the issue.
=> [chart] Template `imagePullSecrets` also they come from `global`

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/_helpers.tpl, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/rolebinding.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/serviceaccount.yaml, charts/nri-metadata-injection/tests/job_serviceaccount_test.yaml, charts/nri-metadata-injection/tests/rbac_test.yaml
There is an issue open by GTS saying that not all the charts honor the flag `.global.serviceAccount.create` and `.global.serviceAccount.name`: newrelic/helm-charts#875
There is not also the issue that they are not honored by the deployments but also by the jobs that create and patch webhook certificates.
=> [helm chart] Patch job should also honor the global service account flag

.github/workflows/release-integration.yml, .github/workflows/security.yaml, Dockerfile
In https://github.com/newrelic/nri-kubernetes/pull/517 I removed high vulnerabilities following the approach of https://github.com/newrelic/infrastructure-bundle/pull/207.
I think that was a mistake. In nri-bundle it makes sense since it is a collection of binaries and it would be too chatty. Here we can address vulnerabilities and if needed add them to the `.trivyignore` file with an explanation
=> fix(trivy): re-enable trivy for high vulnerabilities

.github/workflows/release-integration.yml
We started to unify all the linting/testing processes through all the integrations.
Sustainability improved a lot, but in this repository, we forgot to refactor the release pipeline.
[`lint` make target was removed](https://github.com/newrelic/k8s-metadata-injection/commit/93e621342629ebb6f5b9801d45016ce352638cbf#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L40-L42) to use directly the `golangci-lint` action but we forgot to remove that from the release pipeline.
This PR should fix that issue.
=> There is no `lint` make target anymore

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
Relates to https://github.com/newrelic/helm-charts/issues/932.
NodeSelectors are not being honoured in the jobs objects.
=> NEWRELIC-3912 Add nodeSelector support for jobs

src/server/webhook.go, src/server/webhook_test.go
Because of https://github.com/newrelic/k8s-metadata-injection/actions/runs/3378535842.
=> Remove io/ioutil for io and os packages

charts/nri-metadata-injection/Chart.yaml
Follow up PR of https://github.com/newrelic/k8s-metadata-injection/pull/236. 
Do not merge until the release `v1.7.4` is done.
=> Bump chart

.github/workflows/push_pr.yml, charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/README.md, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/clusterrole.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/psp.yaml, charts/nri-metadata-injection/values.yaml
PSPs are removed in 1.25. Attempting to install this chart in 1.25 will result in an error, as the object the chart attempts to create does not exist in the cluster.
This PR adds a flag to control whether PSPs should be created and disables it by default.
=> chart: disable PSPs by default

charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
According to the error message when a user encountered during newrelic bundle upgrade in this [issue](https://github.com/newrelic/helm-charts/issues/1027) , MutatingWebhookConfiguration is not supported by API version v1beta1. So remove the API version from this MutatingWebhookConfiguration definition.
=> resolve the issue about MutatingWebhookConfiguration being not supported in v1beta1

.github/workflows/release-chart.yml, .github/workflows/repolinter.yml, CHANGELOG.md, charts/nri-metadata-injection/Chart.yaml
Main Changes
- [Resolve the issue about MutatingWebhookConfiguration being not supported in v1beta1](https://github.com/newrelic/k8s-metadata-injection/pull/260)
- merge/include multiple dependency bump PRs as follows
https://github.com/newrelic/k8s-metadata-injection/pull/249
https://github.com/newrelic/k8s-metadata-injection/pull/250
https://github.com/newrelic/k8s-metadata-injection/pull/253
https://github.com/newrelic/k8s-metadata-injection/pull/254
https://github.com/newrelic/k8s-metadata-injection/pull/256
https://github.com/newrelic/k8s-metadata-injection/pull/258
https://github.com/newrelic/k8s-metadata-injection/pull/259
https://github.com/newrelic/k8s-metadata-injection/pull/262
=> bump chart version and include a chart releaser action version change

.github/ct.yaml, .github/workflows/release-chart.yml
This PR makes it easier to make changes to the helm chart without needing to also bump the version in the same PR.
=> Disable Helm chart version check

charts/nri-metadata-injection/Chart.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
As described at https://github.com/newrelic/k8s-metadata-injection/issues/192
When using istio side car injection the hooks get stuck since the istio container never stops. This PR will provide a way of setting the annotations in the hook to avoid such side car.
=> #192 Added hook podAnnotations

charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/nri-metadata-injection/values.yaml
Fixes #274.
k8s.gcr.io image registry will be redirected to registry.k8s.io on Monday March 20th.
All images available in k8s.gcr.io are available at registry.k8s.io.
See https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
=> Update Kubernetes image registry

.github/renovate.json5, .github/workflows/changelog.yml, CONTRIBUTING.md
We need to skip running the changelog workflow for dependency bump prs and for any prs that don't need a changelog like updating the codeowners files for example.
- Updated changelog workflow to not run if a pr has a label of dependencies or Skip Changelog.
- Updated renovatebot to add a label of "dependencies". Note: dependabot already adds this label.
Not applicable for this pr.
=> chore: Add labels to changelog workflow and renovatebot 

CHANGELOG.md, charts/nri-metadata-injection/templates/cert-manager.yaml, charts/nri-metadata-injection/values.yaml
When we set `certManager.enabled: true` and deploy this via ArgoCD there is a diff error that occurs as the API returns:
- duration `43800h0m0s` for the root certificate
- duration `8760h0m0s` for the webhook certificate
This PR allows us to configure these exact values and match what the API is returning thus removing the diff.
n/a
=> fix: configuration of cert-manager cert durations

.github/workflows/release-integration.yml, CHANGELOG.md
Security compliance: [SECREV-2969](https://newrelic.atlassian.net/browse/SECREV-2969)
Pin third party action version using a full length SHA to meet security standards.
=> SECREV-2969: pin the action version using a full length SHA

.github/workflows/trigger_prerelease.yml
We don't have a `build/Dockerfile` so we need to replace it with use `Dockerfile` in the trigger prerelease workflow. 
- Fixed  `rt-included-files` to use `Dockerfile` instead of `build/Dockerfile`
NA
=> chore: fix dockerfile in trigger prerelease workflow

.github/workflows/changelog.yml
This PR fixes the issue where the changelog workflow was running for renovatebot prs even though they had the "dependencies" label. This issue was happening because the label needs to be added before the pr is created which is not how renovate configuration works. 
So this pr just adds another check that if the head ref branch of the pr contains "renovate", then the workflow will not run. 
- Add a check to see if the head ref branch starts with "renovate".
NA
=> Exclude renovate changelog

.github/workflows/push_pr.yml
Removing old version of k8s from push_pr workflow. It looks like k8s version 1.16.15 is having kubelet check issues. We're in the middle of deprecating old k8s versions so we will remove this version from this workflow for now. 
- Removed 1.16.15 version from k8s-matrix
=> fix: Remove k8s version 1.16.15 from push_pr workflow

.github/workflows/changelog-reusable.yml, .github/workflows/changelog.yml
Test using reusable workflow for changelog
=> temp: Add reusable changelog workflow

.github/workflows/release-chart-reusable.yml, .github/workflows/release-chart.yml, .github/workflows/release-integration-reusable.yml, .github/workflows/security.yaml, .github/workflows/trigger-prerelease-reusable.yml
Automate workflow notifications to Slack. That way we have only one source of truth to check for failing workflows.
For workflows that run for PRs, there is no need for automatic Slack notifications since merging will be blocked in the corresponding PR and author will be notified.
=> ci: Add Slack notifications to all workflows that do not involve pull requests

.github/workflows/security.yaml
Updates workflow to remove deprecated flag and to notify on failure only when trigger on a schedule.
=> ci: Update 'Security Scan' workflow

.github/workflows/security.yaml
Now that testing is done, revert testing changes.
=> ci: Revert testing code in 'Security Scan' workflow

.github/workflows/release-integration-reusable.yml, CHANGELOG.md
- It is confusing to download a specific repo in a reusable workflow. This PR makes it explicit that we are only interested in fetching a single file to allow us find the next version to use
- Pass through environment variables used to initialize first container log line
=> ci: Make explicit that we are only using a single file

.github/workflows/release-integration-reusable.yml, CHANGELOG.md
Flag `--build-arg` does not handle spaces, so quotations are needed to avoid error:
```
ERROR: "docker buildx build" requires exactly 1 argument.
```
=> fix: Add quotation to variables to handle spaces

.github/workflows/release-integration-reusable.yml, CHANGELOG.md
The release pipeline workflow is currently only including build-time metadata in the prerelease image. This PR adds the same metadata to the release image.
=> fix: Fix release workflow to include build-time metadata on release image

charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
If a webhook is intercepting any resources in system-managed namespaces, or certain types of resources, they can be considered unsafe
Some information for GKE deployments https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?_ga=2.102213761.-1408611334.1679870533#unsafe-webhooks
So if injectOnlyLabeledNamespaces is true, the scope should be Namespaced not "*"
=> Unsafe webhooks

.github/workflows/release-integration-reusable.yml
Some repos use a different key name for the image. The prom-config uses `configuratorVersion` while other repos like nri-kubernetes repo uses `appVersion`.
=> fix: Refactor image name key in open pr job

.github/workflows/release-integration-reusable.yml, CHANGELOG.md
We run Trivy scans on the security workflow, so it is counterproductive to block a release after a CVE is found
=> ci: Trivy scans should only run on the 'Security' workflow

.github/workflows/security-reusable.yaml, CHANGELOG.md
Upload SARIF report from Trivy when running the 'Security' workflow in the `schedule` or `push` to `main` events. This will guarantee that once a vulnerability is fixed the Security tab on GitHub will be reflecting that.
=> feat: Upload sarif when running periodically or pushing to main

.github/workflows/security-reusable.yaml, CHANGELOG.md
When Trivy runs on repo mode it does not check the base image in the `Dockerfile`. By using image mode, we get vulnerability reports for both the repo and any issues detected in the Docker image
=> feat: Improve Trivy scan by using Docker image

.github/workflows/release-chart-reusable.yml, .github/workflows/release-integration-reusable.yml, .github/workflows/security-reusable.yaml, .github/workflows/trigger-prerelease-reusable.yml, CHANGELOG.md
Following security standards, we need to pin actions to hash values (immutable), not tags (mutable). This PR addresses this issue first for the Slack notification action.
=> fix: Pin Slack notification action to a hash, not to a tag

CHANGELOG.md, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
A customer recently reported that `allowPrivilegeEscalation=false` wasn't working on the admission webhooks in k8s-metadata-injection. This change allows `containerSecurityContext` to be passed into the admission webhook job templates as it is in the deployment.
Logs look normal & metadata is added to new pods as expected
```
kn logs newrelic-bundle-nri-metadata-injection-admission-create-mpm6b
W0515 19:12:01.304876       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"secrets \"newrelic-bundle-nri-metadata-injection-admission\" not found","level":"info","msg":"no secret found","source":"k8s/k8s.go:229","time":"2025-05-15T19:12:01Z"}
{"level":"info","msg":"creating new …
```
=> chore: add container security context to admission webhook jobs
