newrelic/k8s-metadata-injection

- main.go
Output sample: 
```
{"level":"info","ts":1549279957.7872293,"caller":"app/main.go:129","msg":"POST https://newrelic-metadata-injection-svc.default.svc:443/mutate?timeout=30s HTTP/2.0\" from 10.0.2.15:36386"}
```
> Logging Middleware that logs every request

- e2e-tests/k8s-e2e-bootstraping.sh
- e2e-tests/tests.sh
This makes easier to understand the tests, and also will allow us to reuse the bootstrapping code in other projects.
> Extract e2e bootstraping

- README.md
Adds more information for people that wish to contribute to the k8s metadata injection project.
> Add 'Contributing' section in the README

- .github/workflows/build.yml
- CHANGELOG.md
- Makefile
- deploy/job.yaml
- deploy/newrelic-metadata-injection.yaml
Updating cert manager to include following fix https://github.com/newrelic/k8s-webhook-cert-manager/releases/tag/v1.3.2
> feat(certManager): update to 1.3.2

- .github/workflows/push_pr.yml
- .github/workflows/release-chart.yml
I copied an outdated pipeline without realising it was templated yet.
> fix(index): templating index check

- .github/workflows/push_pr.yml
Follow up of https://github.com/newrelic/nri-kubernetes/pull/388/files
> fix(ci/cd): fail if version is missing

- README.md
Fixes https://github.com/newrelic/k8s-metadata-injection/issues/263
> Update community header

- charts/nri-metadata-injection/Chart.yaml
Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>
> Bump Helm chart version

- .github/renovate.json5
Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>
> Update rennovate workflow

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Add a template for pull requests to standardize them.
> chore: Add Pull Request Template

- CHANGELOG.md
- src/server/webhook.go
Add more logs related to NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME injection to help customer debug their issue.
> Add More Logs for NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME Injection

- charts/nri-metadata-injection/README.md
> Document certificate duration values

- charts/nri-metadata-injection/Chart.yaml
> Bump versions

- .github/workflows/changelog.yml
Temporarily adding a debug step to changelog workflow to debug issues with it running for prs with dependencies label.
> tmp: Add debug step to changelog workflow

- .github/workflows/trigger_prerelease.yml
- CHANGELOG.md
Define GitHub bot name and email so commits are signed using the correct bot.
> Define GitHub bot name and email

- Dockerfile
> testing: Lower dockerfile version

- charts/nri-metadata-injection/Chart.yaml
Bump versions. 
- Bump version and appVersion in chart.yaml
> chore: Bump version and app version

- .github/actions/version-bump/action.yml
- .github/actions/version-bump/version-update.js
- .github/workflows/release-integration.yml
This PR is testing adding a new composite action to find the new helm chart version based on the new appVersion. 
And this PR updates the release-integration workflow to create a pr with these new versions. 
> tmp: Testing new workflow to bump versions

- CHANGELOG.md
- charts/nri-metadata-injection/Chart.yaml
Remove old maintainers from chart file
NA
> Update Chart.yaml list of maintainers

- .github/workflows/push_pr.yml
- .github/workflows/release-integration.yml
Fixes minor typo and expands flags to help with script readability.
> fix: Fix typo

- .github/workflows/changelog.yml
- .github/workflows/release-chart-reusable.yml
- .github/workflows/release-chart.yml
Fix release chart workflow and changelog workflow
> Temp: Fix release chart and changelog workflow

- CHANGELOG.md
- CONTRIBUTING.md
Made a minor change to the contributing docs to test workflows again after repo setting update. 
- Updated contributing.md file
NA
> chore: Update CONTRIBUTING.md doc

- .github/workflows/release-chart-reusable.yml
- .github/workflows/release-integration-reusable.yml
Adding permissions to test workflows that need read/write permissions. 
> Temp: Add permissions

- .github/workflows/release-chart-reusable.yml
- .github/workflows/release-chart.yml
- .github/workflows/release-integration-reusable.yml
- .github/workflows/release-integration.yml
Fix permissions to be set in the correct workflow. 
> Fix: Move permissions to correct workflow

- CHANGELOG.md
Reverting changelog for testing workflows
> testing: Update CHANGELOG.md

- .github/workflows/release-integration-reusable.yml
Need to troubleshoot failing action
> Tmp: Update release-integration-reusable.yml

- .github/workflows/release-integration-reusable.yml
Test increasing timeout and adding cache. 
> tmp: Increase timeout and add cache to release integration workflow

- .github/workflows/release-integration-reusable.yml
Add debug steps to workflow to help with troubleshooting. 
> Tmp: Add debug steps

- .github/workflows/release-integration-reusable.yml
Update go file path to full path instead of relative.
> fix: Fix path in go file in job

- .github/workflows/release-integration-reusable.yml
Checkout repo before calling golang file in open-pr job
> fix: Fix golang file path open-pr job

- .github/workflows/release-integration-reusable.yml
Update open-pr job to checkout repo where charts are stored. 
> fix: Checkout passed in repo in release integration workflow

- .github/workflows/security.yaml
Security workflow is failing due to permission issues. Testing the solution by adding permissions. 
> fix: Add permissions to security workflow

- .github/workflows/release-integration-reusable.yml
- .github/workflows/release-integration.yml
- CHANGELOG.md
Done testing removing `bin` from artifact path. This pr puts `bin` path into path. 
> fix: Add bin back to artifact path

- .github/workflows/security.yaml
Updates Slack notification to fix wrong URL
> ci: Fix Slack notification for 'Security Scan' workflow

- .github/PULL_REQUEST_TEMPLATE.md
> ci: Simplify PR template

- .github/workflows/security.yaml
> ci: Update 'Security Scan' permissions

- .github/workflows/security.yaml
Reduce redundant code and simplify code maintenance by making the security workflow reusable.
> ci: Use reusable 'Security Scan' workflow

- .github/workflows/release-integration-reusable.yml
- CHANGELOG.md
Checkout `version-update.go` in its own directory to avoid clashing with the other checkout that checks the whole repo
> fix: Fix action to fetch `version-update.go`

- .github/workflows/release-integration-reusable.yml
- CHANGELOG.md
Make explicit on the checkout action which repo needs to be downloaded, since we are downloading two repos in the same job.
> ci: Improve readability of `release-integration-reusable.yml`

- .github/workflows/release-integration-reusable.yml
Linting code is an exercise to guarantee only high-quality code is merged to the main branch, not to stop the release process.
> fix: Linting should be enforced at the PR level, not during the release process

- .github/renovate.json5
> fix: Fix renovate config file

- .github/workflows/release-chart-reusable.yml
- .github/workflows/release-integration-reusable.yml
- .github/workflows/security-reusable.yaml
- .github/workflows/trigger-prerelease-reusable.yml
> ci: Update Slack actions version

- .github/workflows/push_pr.yml
Updating minikube version so Helm chart linting works for Kubernetes v 1.27
> ci: Update minikube version

- .github/workflows/release-integration-reusable.yml
Add auto merge to version bump prs.
> chore: Add pr auto merge for bumping chart versions

- .github/workflows/release-integration-reusable.yml
Add Skip Changelog label to Bump versions pr.
> fix: Add label to pr in release-integration-reusable.yml

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Remove 1.23 support

- .github/workflows/security-reusable.yaml
> fix: Create SARIF file before attempting to upload it

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Add k8s v1.28.0-rc.1 support

- .github/workflows/push_pr.yml
Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)
> fix: Disable semgrep action that has been deprecated

- .github/renovate-base.json5
- .github/renovate.json5
Add a renovate base json file that other k8s agents repos will use.
> feat: Add renovate base json file

- .github/renovate.json5
> fix: Add renovate file

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Replace k8s v1.28.0-rc.1 with k8s 1.28.3 support

- .github/workflows/test-prerelease.yml
> Check out repository first in workflow

- renovate-base.json5
Update renovate base config file to include Helm's `values.yaml` files
> ci: Update renovate base config file

- renovate-base.json5
> feat: Update renovate config

- .github/workflows/push_pr.yml
- .github/workflows/test-prerelease.yml
> Workflow WIP

- .github/workflows/test-prerelease.yml
> fix script ref

- .github/workflows/test-prerelease.yml
> remove working directory from defaults

- .github/workflows/push_pr.yml
- .github/workflows/test-prerelease.yml
> Update workflow push_pr WIP 

- .github/workflows/push_pr.yml
- .github/workflows/test-prerelease.yml
- Makefile
- e2e-tests/tests.sh
> trigger e2e release tests through makefile

- .github/workflows/push_pr.yml
- .github/workflows/test-prerelease.yml
> indentation issues

- e2e-tests/release-tests.sh
> new script

- e2e-tests/release-tests.sh
- e2e-tests/tests.sh
> fix image references

- e2e-tests/release-tests.sh
> try running explicitly in bash for ubuntu

- .github/workflows/push_pr.yml
- .github/workflows/test-prerelease.yml
- e2e-tests/release-tests.sh
- e2e-tests/tests.sh
> Working Prerelease testing workflow

- .github/workflows/changelog.yml
- .github/workflows/release-chart.yml
- .github/workflows/release-integration.yml
- .github/workflows/security.yaml
- .github/workflows/trigger-prerelease.yml
- CHANGELOG.md
Update reusable workflow dependency
> feat: Update reusable workflow dependency

- .github/workflows/push_pr.yml
- CHANGELOG.md
- Makefile
- README.md
> ci: add codecov

- charts/nri-metadata-injection/Chart.yaml
- charts/nri-metadata-injection/README.md
> chore: update maintainers

- .github/workflows/push_pr.yml
> chore: update codecov config

- .github/workflows/release-integration.yml
> chore: Update secrets

- CHANGELOG.md
- charts/nri-metadata-injection/values.yaml
> update kube-webhook-certgen cve

- go.mod
- src/server/webhook_test.go
I somehow closed the renovate branch that updated the Go version. So here's a new one!
> chore: update go version
